### Find All Content
GET http://localhost:8080/api/content

### Get Content by ID
GET http://localhost:8080/api/content/{{id}}

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "My Second Blog post",
  "description": "That is my second blog post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-11-07T13:20:38.243630279",
  "dateUpdated": null,
  "url": ""
}
